store/config/routes.rb
Store::Application.routes.draw do
  resources :products
  root :to => "products#index"

end

store/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :released_at
  
  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  def index
    @products = Product.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "Successfully created product."
      redirect_to @product
    else
      render :action => 'new'
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      flash[:notice] = "Successfully updated product."
      redirect_to @product
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Successfully destroyed product."
    redirect_to products_url
  end
  
  private
  
  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

store/app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

store/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

store/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

store/app/helpers/products_helper.rb
module ProductsHelper
end

store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

store/app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :released_at %><br />
    <%= f.datetime_select :released_at %>
  </p>
  <p><%= f.submit %></p>
<% end %>

store/app/views/products/_products.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="pretty">
  <tr>
    <th><%= sortable "name" %></th>
    <th><%= sortable "price" %></th>
    <th><%= sortable "released_at", "Released" %></th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= product.name %></td>
      <td class="price"><%= number_to_currency(product.price) %></td>
      <td><%= product.released_at.strftime("%B %e, %Y") %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @products %>

store/app/views/products/edit.html.erb
<% title "Edit Product" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @product %> |
  <%= link_to "View All", products_path %>
</p>

store/app/views/products/index.html.erb
<% title "Products" %>

<%= form_tag products_path, :method => 'get', :id => "products_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="products"><%= render 'products' %></div>
<% end %>



<p><%= link_to "New Product", new_product_path %></p>

store/app/views/products/index.js.erb
$("#products").html("<%= escape_javascript(render("products")) %>");

store/app/views/products/new.html.erb
<% title "New Product" %>

<%= render 'form' %>

<p><%= link_to "Back to List", products_path %></p>

store/app/views/products/show.html.erb
<% title "Product" %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Released At:</strong>
  <%= @product.released_at %>
</p>

<p>
  <%= link_to "Edit", edit_product_path(@product) %> |
  <%= link_to "Destroy", @product, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", products_path %>
</p>